### ISSUE TITLE
Could you add more templating for the README?

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/cookiecutter-my-lab-to-nwb-template#1]

**Comment by h-mayorquin** [comment]
I did not see this before. Addressing it now.

**Comment by h-mayorquin** [comment]
@bendichter 
Check out the results in:
https://github.com/catalystneuro/seidemann-lab-to-nwb/tree/add_readme

This was generated automatically with the latest changes here

**Comment by h-mayorquin** [comment]
This is addressed, let me know if you have other suggestions.
