### ISSUE TITLE
[ToDo] Polish labels

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/cookiecutter-my-lab-to-nwb-template#6]
I'm pretty sure copies of this template inherit everything, including labels. Should make those as consistent with upstream stuff, and as polished as possible.

**Comment by CodyCBakerPhD** [comment]
This is most useful for the project boards, which offer summary statistics conditional on assigned labels

**Comment by h-mayorquin** [comment]
Cody, I don't understand this one. What labels are you referring to?

**Comment by CodyCBakerPhD** [comment]
Only works when copying from a repo template, not a cookiecutter. Closing
